name: deploy
on:
    push:
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
              with:
                  submodules: recursive
                  token: ${{ secrets.TOKEN }}
            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: latest
            - name: setup pandoc
              run: sudo apt-get install -y pandoc
            - name: install
              run: npm install
            - name: build
              run: npm run build
            - name: deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  personal_token: ${{ secrets.TOKEN }}
                  external_repository: argvchs/argvchs.github.io
                  publish_branch: master
